<?php
/**
 * @see PagarMe_Pix_Block_Success
 */
$helper = Mage::helper('pagarme_pix');
?>

<?php if ($this->isPixPayment()): ?>
    <?php if ($qrCode = $this->getQrCode()): ?>
        <div class="qr-code">
            <div><?= $qrCode ?></div>
            <div style="display: inline-block;">
                <svg style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0; width: 20px"
                     aria-hidden="true"
                     focusable="false" data-prefix="fas" data-icon="copy" class="svg-inline--fa fa-copy fa-w-14"
                     role="img"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                    <path fill="blue"
                          d="M320 448v40c0 13.255-10.745 24-24 24H24c-13.255 0-24-10.745-24-24V120c0-13.255 10.745-24 24-24h72v296c0 30.879 25.121 56 56 56h168zm0-344V0H152c-13.255 0-24 10.745-24 24v368c0 13.255 10.745 24 24 24h272c13.255 0 24-10.745 24-24V128H344c-13.2 0-24-10.8-24-24zm120.971-31.029L375.029 7.029A24 24 0 0 0 358.059 0H352v96h96v-6.059a24 24 0 0 0-7.029-16.97z">
                    </path>
                </svg>
                <a id="pagarme_pix_copy"
                   style="display: inline-block; vertical-align: middle; margin: 0 5px 0 0;"><?= $helper->__('Copy PIX code') ?></a>
                <input style="opacity: 0; user-select: none; pointer-events: none;" type="text" value="<?= $qrCode ?>"
                       id="pagarme_pix_qr_code"/>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<script>
    jQuery(document).ready(function () {
        try {
            jQuery('#pagarme_pix_copy').click(function () {
                var copyText = document.getElementById('pagarme_pix_qr_code');

                copyText.select();
                copyText.setSelectionRange(0, 99999);
                document.execCommand("copy");

                alert("<?= $helper->__('PIX code copied')?>");
            });
        } catch (e) {
            console.error(e);
        }
    });
</script>