<?php
/**
 * @see PagarMeV5_Boleto_Block_Success
 */
?>

<?php if ($this->isBoletoPayment()): ?>
    <p class="pagarmev5_boleto_info_boleto">
    <?php echo Mage::helper('pagarmev5_boleto')->__('Click the followed link to print your boleto') ?>
        <a target="_blank" href="<?php echo $this->getBoletoUrl(); ?>">
            <?php echo Mage::helper('pagarmev5_boleto')->__('click here') ?>
        </a>
    </p>
<?php endif; ?>
