<?php if ($this->isBoletoPayment()): ?>
    <?php if($url = $this->getBoletoUrl()): ?>
        <p class="pagarmev5_boleto_info_boleto">
            <?php echo Mage::helper('pagarmev5_boleto')->__('Click the followed link to print your boleto') ?>
            <a target="_blank" href="<?php echo $url ?>">
                <?php echo Mage::helper('pagarmev5_boleto')->__('click here') ?>
            </a>
        </p>
	<?php endif; ?>
<?php endif; ?>
