<?php
/**
 * @see PagarMeV5_Boleto_Block_Info
 */
$helper = Mage::helper('pagarmev5_boleto');
?>
<h3><?php echo $helper->__('Pagar.me Boleto'); ?></h3>
<table id="pagarme_order_info_payment_details">
    <tr>
        <td>
            <strong>
			    <?php echo $helper->__('Pagar.me Order Id'); ?>
            </strong>
        </td>
        <td style="text-align:right;"><?= $this->getOrderId(); ?></td>
    </tr>
    <tr>
        <td class="label">
            <strong>
                <?php echo $helper->__('Pagar.me Transaction Id');?>
            </strong>
        </td>
        <td style="text-align:right;"><?= $this->getTransactionId(); ?></td>
    </tr>
    <tr>
        <td class="label">
            <strong><?php echo $helper->__('Boleto Url'); ?></strong>
        </td>
        <td style="text-align: right" class="value">
            <a href="<?php echo $this->getBoletoUrl(); ?>" target="_blank">
                <?php echo $helper->__('Show boleto'); ?>
            </a>
        </td>
    </tr>
</table>
